### ISSUE TITLE
关于wbsign.json

### ISSUE THREAD

**Issue by Disky** [rhming/UnicomDailyTask#21]
wbsign.json 这个文件里是什么数据，看了一下代码还是没搞太明白

**Comment by rhming** [comment]
刷微博的积分任务，有个参数未分析出，需要frida调试得到sign或者抓包获取 这个值根据设备生成固定值

**Comment by Disky** [comment]
微博积分任务还是搞不定，sign是根据设备生成的，抓包获取的sign怎么能用到云函数上呢，参数不同sign就不一样

**Comment by rhming** [comment]
查看[issue13](https://github.com/rhming/UnicomDailyTask/issues/13),这个issue里面有步骤,需要替换成自己的设备信息或frida调试

**Comment by Disky** [comment]
伪装AndroidId后抓包，修改了几句代码，微博签到多账号测试正常了

**Comment by gitiray** [comment]
微博任务应该是结束，不再显示了

**Comment by rhming** [comment]
> 
年底了 积分任务开始陆续过期
