### ISSUE TITLE
请问这样是成功么 输出没有日志

### ISSUE THREAD

**Issue by Silentely** [rhming/UnicomDailyTask#3]
部署后测试 没有日志显示，pythonanywhere里也没有数据
![](https://s3.bmp.ovh/imgs/2021/09/ac9f04d043c9a914.png)
![](https://s3.bmp.ovh/imgs/2021/09/12399c3b46673095.png)

**Comment by rhming** [comment]
活动执行时间在代码中是固定的,不在时间段不会执行任务,活动基本上午执行完,云函数触发配置更改了,代码中的活动时间也要更改(活动执行时间在index,py)

**Comment by Silentely** [comment]
> 活动执行时间在代码中是固定的,不在时间段不会执行任务,活动基本上午执行完,云函数触发配置更改了,代码中的活动时间也要更改(活动执行时间在index,py)

看到了 确实是定时时间内运行有日志
