### ISSUE TITLE
请问我测试出来这个，怎么解决，是哪里错了？

### ISSUE THREAD

**Issue by angelfish110** [rhming/UnicomDailyTask#31]
![QQ截图20211123191107](https://user-images.githubusercontent.com/33411707/143014364-b1282fd2-168c-499c-b70e-352b9a9001ef.png)

def PushTemplate():
    # 消息推送 (读取数据存储服务记录的日志进行推送)
    # utils/config.py 推送配置
    # 填写参与活动任务的账号
    # 不需要推送 可以不填
    PushLog([
        # "18615941687",
        # "联通手机号-2",
        # "18615941687",
        # "沃邮箱mobile-2",
    ]).run()

  # server酱推送 参考文档 https://sct.ftqq.com/sendkey api参数详细说明
    # 需在server酱 配置消息通道 默认微信方糖公众号接收
    # channel 方糖服务号=9、Android=98、Bark iOS=8、企业微信群机器人=1、钉钉群机器人=2、飞书群机器人=3、测试号=0、自定义=88、企业微信应用消息=66
    "ftqq": {
        "sendkey": "SCU15352T5b5b131c07b605a22f6iicm1d7a25b3da55a000207da6b",  # server酱 SendKey
        "channel": "9",  # 指定消息通道 选填 最多可选两个 以`|`分割 例如: 1|2
        "openid": "",  # 消息抄送的openid 选填 企业微信群中成员账号名
    }

我这样填 对吗？

**Comment by rhming** [comment]
号码前面的`#`是注释,把它去掉
现在执行任务不在时间范围内不会执行,可以将`index.py`文件里的`DEBUG = False`改成`DEBUG = True`开启调试默认,会执行全部任务,执行完再改回去

**Comment by angelfish110** [comment]
请问我这个SERVER推送对吗？是这样填 的吗？谢谢

**Comment by rhming** [comment]
是的,微信方糖公众号接收推送

**Comment by angelfish110** [comment]
好的，明天我在看看，谢谢解答

**Comment by angelfish110** [comment]
> 是的,微信方糖公众号接收推送

**Comment by angelfish110** [comment]
进入网站 用户名.pythonanywhere.com 添加数据测试 点击管理后台登录查看数据， 这个没看懂，到底怎么弄，怎么添加数据测试？？我该点哪个？？

![QQ截图20211124115500](https://user-images.githubusercontent.com/33411707/143172766-d89a5680-1e51-4adb-bda5-7416f34d65fb.png)

![QQ截图20211124115822](https://user-images.githubusercontent.com/33411707/143172739-89ef22b5-5b45-408f-87a1-ac1dc54edf5e.png)
谢谢

**Comment by rhming** [comment]
点击HTML form会有两个输入框 点击POST提交数据成功 就可以在后台看到

**Comment by angelfish110** [comment]
这样就对了吗？
![QQ截图20211124123655](https://user-images.githubusercontent.com/33411707/143175874-946e1ac2-1664-4a26-82d7-f8b8bb0dfe6c.png)
还有 PushLog([
        # "联通手机号-1",
        # "联通手机号-2",
        # "沃邮箱mobile-1",
        # "沃邮箱mobile-2",
    ]).run()
{
  "手机号-1": "联通appId-1",
  "手机号-2": "联通appId-2"
}

deviceIds = {
    'mobile-1': 'imei-1',
    'mobile-2': 'imei-2',
是把联通手机号，沃邮箱mobile，联通appId，手机号，mobile，imei替换吗？后面那个-1 和-2留着吗？

**Comment by rhming** [comment]
那只是举例有多个手机号,都替换掉

**Comment by angelfish110** [comment]
> 那只是举例有多个手机号,都替换掉,不用保留
好的，我试试 ，谢谢
