### ISSUE TITLE
提供活动

### ISSUE THREAD

**Issue by gitiray** [rhming/UnicomDailyTask#33]
可用积分，看视频，进入后
- 看视频得积分：每30秒1分，每天共20分
- 点赞视频：点赞3次各1分，每天共3分

签到，话费红包
- 看视频：每天3次

**Comment by rhming** [comment]
已添加活动任务

**Comment by gitiray** [comment]
提个小建议，看视频得积分现在限制每月100分上限，做任务之前检测判断是否达到上限，以免继续重复请求被拉黑

**Comment by rhming** [comment]
看视频100积分有`monthTopLimit`判断当月是否已到达限制

**Comment by gitiray** [comment]
沃音乐彩铃又增加了每日浏览6积分、每月参与话题4积分这两个活动，请大佬看下搞得了不

**Comment by rhming** [comment]
已添加了活动

**Comment by rhming** [comment]
更新只需替换`activity/womusic`路径下的两个文件就行

**Comment by gitiray** [comment]
大佬牛逼！

> 已添加了活动
