### ISSUE TITLE
双十一的签到好像失效了，只有抽奖在跑，大佬有空看一下吗

### ISSUE THREAD

**Issue by rbzan** [rhming/UnicomDailyTask#35]

**Comment by onesixsix** [comment]
的确，刚看了一下，没签到

**Comment by rbzan** [comment]
> 的确，刚看了一下，没签到

Ac-leijiqiandao2改成Ac-leijiqiandao3就可以了，哈哈还是自己太懒了，刚刚抓包看了下

**Comment by rhming** [comment]
已经修复了 可以直接覆盖替换掉`activity/unicom/qiandao11.py`文件

**Comment by rbzan** [comment]
感谢大佬
