### ISSUE TITLE
微博任务有点诡异啊

### ISSUE THREAD

**Issue by rbzan** [rhming/UnicomDailyTask#40]
用雷电模拟器抓了5个设备的参数，一开始几天5个号都能完成，今天发现就完成了两个号，手动跑了下发现cardlist是有数据出来的，但是任务就是没完成，然后又重新用雷电模拟器抓了3个设备，可以完成了，就是过几天不知道会不会又失效了

**Comment by rbzan** [comment]
代码有略微改动下
[https://raw.githubusercontent.com/rbzan/v2ray-heroku/master/QQ%E6%8B%BC%E9%9F%B31.jpg](url)
[https://raw.githubusercontent.com/rbzan/v2ray-heroku/master/QQ%E6%8B%BC%E9%9F%B32.jpg](url)

**Comment by rhming** [comment]
可能那段时间接口在维护或者网络波动之类的
我看了一下今天微博任务那段日志出现网络问题也没完成 刚跑了一下都领取成功了

**Comment by rbzan** [comment]
我在同一时间段，用另一套设备信息就能领，奇怪

**Comment by rbzan** [comment]
> 可能那段时间接口在维护或者网络波动之类的 我看了一下今天微博任务那段日志出现网络问题也没完成 刚跑了一下都领取成功了



> 可能那段时间接口在维护或者网络波动之类的 我看了一下今天微博任务那段日志出现网络问题也没完成 刚跑了一下都领取成功了

我在同一时间段，用另一套设备信息就能领，奇怪
