### ISSUE TITLE
今天登录了沃邮箱网页版，发现有个积分最多的任务没自动做

### ISSUE THREAD

**Issue by allindusk** [rhming/UnicomDailyTask#43]
![image](https://user-images.githubusercontent.com/53708220/145705402-b52a60b2-4262-4e53-aec9-5f5476842036.png)

- **如图所示登录5积分的任务有办法添加吗**

**Comment by rhming** [comment]
已添加网页版沃邮箱积分成长任务

**Comment by rhming** [comment]
登录5积分已添加

**Comment by gitiray** [comment]
![图片](https://user-images.githubusercontent.com/84114630/145837130-d7793ded-c04f-4657-9c8b-380b1e64cdb1.png)

登录百度网盘也能获得5分，不需要绑定百度帐号，点击一次邮箱首页这个按钮就好了

![图片](https://user-images.githubusercontent.com/84114630/145837425-a4e5fd2b-dabb-46ba-996e-ac2b31a3b641.png)

**Comment by rhming** [comment]
> ![图片](https://user-images.githubusercontent.com/84114630/145837130-d7793ded-c04f-4657-9c8b-380b1e64cdb1.png)
> 
> 登录百度网盘也能获得5分，不需要绑定百度帐号，点击一次邮箱首页这个按钮就好了
> 
> ![图片](https://user-images.githubusercontent.com/84114630/145837425-a4e5fd2b-dabb-46ba-996e-ac2b31a3b641.png)

已添加，可以直接覆盖`activity/womail/mailxt5.py`文件更新

**Comment by allindusk** [comment]
大佬辛苦，感谢
