### ISSUE TITLE
SuperSimpleTask

### ISSUE THREAD

**Issue by zhifeng456** [rhming/UnicomDailyTask#46]
hi，老哥，如题，这个好像完成不了。

**Comment by rhming** [comment]
我看了一下今天的都完成了
完成不了的具体表现是出现了什么，截个图看看日志

**Comment by zhifeng456** [comment]
谢老哥回复，等我明天试下哈，是不是我自己鼓捣错了啊，我再确认下。
![42EAE769](https://user-images.githubusercontent.com/58244455/145819477-1f1541a0-0dbf-4244-bb50-fe13aa1cd5db.png)

**Comment by zhifeng456** [comment]
老哥帮看看正常吗，就上面那个气泡任务没做，是不是没在这个里面的,里面有个火爆的提示，但是实际是做了，不知道你们的里面有没有。
5:53:17 2021-12-14 15:53:17.949 | INFO     | activity.unicom.superSimpleTask:run:93 - {
15:53:17     "achieve": "0",
15:53:17     "allocation": "1",
15:53:17     "btn": "去完成",
15:53:17     "disPlay": "0",
15:53:17     "floorId": "41e0c4bd71db46499bdde85add93f017",
15:53:17     "id": "41e0c4bd71db46499bdde85add93f017",
15:53:17     "imageUrl": "https:////img.client.10010.com//signinAppH//images/1632664365659.png",
15:53:17     "jfCount": "+1积分",
15:53:17     "provenceLimit": "0",
15:53:17     "provenceLimitRule": "098",
15:53:17     "rewardUrl": "https:////img.client.10010.com//signinAppH//images/1632664369273.png",
15:53:17     "showStyle": "0",
15:53:17     "stitle": "任务完成",
15:53:17     "taskBigType": "CHAO_JIAN_DAN_REN_WU",
15:53:17     "taskId": "72ac2c052fcb46e5b6717846a2b89d1b",
15:53:17     "taskType": "2",
15:53:17     "templateCode": "72ac2c052fcb46e5b6717846a2b89d1b",
15:53:17     "title": "完成右上角气泡区1个定时任务",
15:53:17     "url": "#"
15:53:17 }
15:53:17 2021-12-14 15:53:17.951 | INFO     | activity.unicom.superSimpleTask:run:93 - {
15:53:17     "achieve": "0",
15:53:17     "allocation": "2",
15:53:17     "btn": "去完成",
15:53:17     "disPlay": "0",
15:53:17     "floorId": "6a14b90e6b1b41cc82ff4ce58a0c1a7d",
15:53:17     "id": "6a14b90e6b1b41cc82ff4ce58a0c1a7d",
15:53:17     "imageUrl": "https:////img.client.10010.com//signinAppH//images/1632664476897.png",
15:53:17     "jfCount": "+2积分",
15:53:17     "provenceLimit": "0",
15:53:17     "provenceLimitRule": "098",
15:53:17     "rewardUrl": "https:////img.client.10010.com//signinAppH//images/1632664480515.png",
15:53:17     "showStyle": "0",
15:53:17     "stitle": "任务完成",
15:53:17     "taskBigType": "CHAO_JIAN_DAN_REN_WU",
15:53:17     "taskId": "9e297b6ace2145bd8fcac05662ec50a1",
15:53:17     "taskType": "2",
15:53:17     "templateCode": "9e297b6ace2145bd8fcac05662ec50a1",
15:53:17     "title": "完成右上角气泡区2个定时任务",
15:53:17     "url": "#"
15:53:17 }
15:53:17 2021-12-14 15:53:17.953 | INFO     | activity.unicom.superSimpleTask:run:93 - {
15:53:17     "achieve": "0",
15:53:17     "allocation": "3",
15:53:17     "btn": "去完成",
15:53:17     "disPlay": "0",
15:53:17     "floorId": "5bd0f51e254444deb382f250f5e17522",
15:53:17     "id": "5bd0f51e254444deb382f250f5e17522",
15:53:17     "imageUrl": "https:////img.client.10010.com//signinAppH//images/1632664550074.png",
15:53:17     "jfCount": "+3积分",
15:53:17     "provenceLimit": "0",
15:53:17     "provenceLimitRule": "098",
15:53:17     "rewardUrl": "https:////img.client.10010.com//signinAppH//images/1632664553400.png",
15:53:17     "showStyle": "0",
15:53:17     "stitle": "任务完成",
15:53:17     "taskBigType": "CHAO_JIAN_DAN_REN_WU",
15:53:17     "taskId": "3d54ba3d2f354b20a9844ce42284134a",
15:53:17     "taskType": "2",
15:53:17     "templateCode": "3d54ba3d2f354b20a9844ce42284134a",
15:53:17     "title": "完成右上角气泡区3个定时任务",
15:53:17     "url": "#"
15:53:17 }
15:53:17 2021-12-14 15:53:17.955 | INFO     | activity.unicom.superSimpleTask:run:93 - {
15:53:17     "achieve": "0",
15:53:17     "allocation": "1",
15:53:17     "btn": "去完成",
15:53:17     "disPlay": "0",
15:53:17     "floorId": "ab0f0a756fd94b708a0cd0fe2ba37bdb",
15:53:17     "id": "ab0f0a756fd94b708a0cd0fe2ba37bdb",
15:53:17     "imageUrl": "https:////img.client.10010.com//signinAppH//images/1632665755646.png",
15:53:17     "jfCount": "+1积分",
15:53:17     "provenceLimit": "0",
15:53:17     "provenceLimitRule": "098",
15:53:17     "rewardUrl": "https:////img.client.10010.com//signinAppH//images/1632665759220.png",
15:53:17     "showStyle": "0",
15:53:17     "stitle": "任务完成",
15:53:17     "taskBigType": "CHAO_JIAN_DAN_REN_WU",
15:53:17     "taskId": "b5f69c69010d440aaf5c802953a0b325",
15:53:17     "taskType": "5",
15:53:17     "templateCode": "b5f69c69010d440aaf5c802953a0b325",
15:53:17     "title": "去浏览积分商城",
15:53:17     "url": "https://u.10010.cn/tbN4E"
15:53:17 }
15:53:17 2021-12-14 15:53:17.956 | INFO     | activity.unicom.superSimpleTask:run:100 - 去浏览积分商城
15:53:17 2021-12-14 15:53:17.957 | INFO     | activity.unicom.superSimpleTask:run:101 - 1
15:54:03 2021-12-14 15:54:03.184 | INFO     | activity.unicom.superSimpleTask:accomplishDotask:65 - {
15:54:03     "data": {
15:54:03         "statusCode": "0000",
15:54:03         "statusMsg": "业务处理成功"
15:54:03     },
15:54:03     "msg": "ok!",
15:54:03     "status": "0000"
15:54:03 }
15:54:37 2021-12-14 15:54:37.220 | INFO     | activity.unicom.superSimpleTask:doTask:38 - 去浏览积分商城
15:54:37 2021-12-14 15:54:37.366 | INFO     | activity.unicom.superSimpleTask:doTask:45 - {
15:54:37     "data": {
15:54:37         "statusDesc": "任务失败",
15:54:37         "extra": "0"
15:54:37     },
15:54:37     "msg": "活动过于火爆，请您稍后再试",
15:54:37     "status": "0029"
15:54:37 }
15:54:37 2021-12-14 15:54:37.521 | INFO     | activity.unicom.superSimpleTask:receiveBenefits:71 - {
15:54:37     "data": {},
15:54:37     "msg": "ok!",
15:54:37     "status": "0000"
15:54:37 }
15:55:11 2021-12-14 15:55:11.701 | INFO     | activity.unicom.superSimpleTask:doTask:38 - 去浏览积分商城
15:55:12 2021-12-14 15:55:12.005 | INFO     | activity.unicom.superSimpleTask:doTask:45 - {
15:55:12     "data": {
15:55:12         "prizeCount": "1",
15:55:12         "statusDesc": "任务完成",
15:55:12         "rewardsPrizeName": "额外奖励",
15:55:12         "prizeName": "去浏览积分商城",
15:55:12         "extra": "0",
15:55:12         "prizeType": "netcoin",
15:55:12         "nextToFinishTimes": "1",
15:55:12         "prizeImg": "https://img.client.10010.com/mobileService/view/client/images/signin/uploads/pic/20210927/4c2628c24f24479f81cf3442d132f6fd.png",
15:55:12         "hadFinishTimes": "9",
15:55:12         "prizeId": "8a29ac9c7bb71b73017bf1dcfc3705bd"
15:55:12     },
15:55:12     "msg": "ok!",
15:55:12     "status": "0000"
15:55:12 }
15:55:12 2021-12-14 15:55:12.241 | INFO     | activity.unicom.superSimpleTask:energy:77 - {
15:55:12     "data": {
15:55:12         "beginTime": "20210917000000",
15:55:12         "endTime": "20211231000000",
15:55:12         "eneId": "837a1cfdd22c42498fa3f03eb82e8d88",
15:55:12         "eneName": "话费红包",
15:55:12         "eneTotal": "9",
15:55:12         "maxValue": "10",
15:55:12         "prizeStockList": [
15:55:12             "{'fixNum': 0, 'givePercentage': 0, 'isGet': '1', 'leftStock': 0, 'maxValue': '4', 'prizeId': '8a2989627c230895017c233ec1780139', 'prizeImg': 'https://img.client.10010.com/mobileService/view/client/images/signin/uploads/pic/20210927/24296807a36d4ec6b6c029db4dcb61aa.png', 'prizeName': '0.02元话费红包'}",
15:55:12             "{'fixNum': 0, 'givePercentage': 0, 'isGet': '1', 'leftStock': 0, 'maxValue': '7', 'prizeId': '8a2989627c230895017c233f6a40013a', 'prizeImg': 'https://img.client.10010.com/mobileService/view/client/images/signin/uploads/pic/20210927/bbaeb88610234e9dbee8615618f08ec0.png', 'prizeName': '0.06元话费红包'}",
15:55:12             "{'fixNum': 0, 'givePercentage': 0, 'isGet': '0', 'leftStock': 0, 'maxValue': '10', 'prizeId': '8a2989627c230895017c2340fbb0013b', 'prizeImg': 'https://img.client.10010.com/mobileService/view/client/images/signin/uploads/pic/20210927/2c5f9e911e824d4a94029d71d89cf8e0.png', 'prizeName': '0.88元话费红包'}"
15:55:12         ],
15:55:12         "updateEnd": "15",
15:55:12         "updateStart": "11"
15:55:12     },
15:55:12     "msg": "ok!",
15:55:12     "status": "0000"
15:55:12 }
15:55:53 2021-12-14 15:55:53.537 | INFO     | activity.unicom.superSimpleTask:run:145 - [superEasy]
15:55:53 完成右上角气泡区1个定时任务:去完成---进度:0/1
15:55:53 完成右上角气泡区2个定时任务:去完成---进度:0/2
15:55:53 完成右上角气泡区3个定时任务:去完成---进度:0/3
15:55:53 看2次完整视频:已完成---进度:0/2
15:55:53 完成下载参与斗地主游戏:已完成---进度:1/1
15:55:53 玩4次0元夺宝:已完成---进度:4/4
15:55:53 兑换1次话费红包:已完成---进度:1/1
15:55:53 去浏览积分商城:已完成---进度:1/1
15:55:53 [bigRew]
15:55:53 连续3日进入签到页:进行中...---进度:2/3
15:55:53 连续5日进入签到页:已完成---进度:5/5
15:55:53 连续7日进入签到页:已完成---进度:7/7

**Comment by rhming** [comment]
气泡任务只有在指定范围时间内才开启，其它时间任务不开启不能执行
运行触达器时间设置成 `0 */15 6-15 * * ?` 6点到15点每十五分钟执行一次

**Comment by zhifeng456** [comment]
好的，谢谢老哥，关掉吧
