### ISSUE TITLE
一直提示appid错误，用文件夹unicom下面的appid不行吗？

### ISSUE THREAD

**Issue by fuduxixi** [rhming/UnicomDailyTask#49]
一直提示appid错误，用文件夹unicom下面的appid不行吗？

**Comment by rhming** [comment]
应该是没找到手机号对应的appId,配置文件`utils/appId.json`中一个手机号对应一个appId,配置中不要多了空格之类的,保证配置文件填写正确

**Comment by fuduxixi** [comment]
> 

只有一个账号 一个APPID 没有空格 这个用另一个大佬聚合的签到函数dailycheckin 配置联通APPID就成功了。。

ERROR RequestId:ec82925d-6c8f-4e8e-8df3-2de568a14693 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 120, in main_handler\n    Template(ZSMHAct)  # 7\n  File \"/var/user/index.py\", line 43, in Template\n    ts.append(Thread(target=cls(mobile, password).run))\n  File \"/var/user/activity/wolearn/zsmh.py\", line 11, in __init__\n    super(ZSMHAct, self).__init__(mobile, password)\n  File \"/var/user/activity/wolearn/wolearn.py\", line 13, in __init__\n    super(WoLearn, self).__init__(mobile, password)\n  File \"/var/user/utils/unicomLogin.py\", line 32, in __init__\n    self.login()\n  File \"/var/user/utils/unicomLogin.py\", line 100, in login\n    \"appId\": self.getAppId(),\n  File \"/var/user/utils/unicomLogin.py\", line 64, in getAppId\n    raise Exception('[UnicomClient]获取appId失败')\nException: [UnicomClient]获取appId失败","statusCode":430}

END RequestId:ec82925d-6c8f-4e8e-8df3-2de568a14693

Report RequestId:ec82925d-6c8f-4e8e-8df3-2de568a14693 Duration:1291ms Memory:128MB MemUsage:63.476562MB

**Comment by fuduxixi** [comment]
> 应该是没找到手机号对应的appId,配置文件`utils/appId.json`中一个手机号对应一个appId,配置中不要多了空格之类的,保证配置文件填写正确

只有一个账号 一个APPID 没有空格 这个用另一个大佬聚合的签到函数dailycheckin 配置联通APPID就成功了。。

ERROR RequestId:ec82925d-6c8f-4e8e-8df3-2de568a14693 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n File "/var/user/index.py", line 120, in main_handler\n Template(ZSMHAct) # 7\n File "/var/user/index.py", line 43, in Template\n ts.append(Thread(target=cls(mobile, password).run))\n File "/var/user/activity/wolearn/zsmh.py", line 11, in init\n super(ZSMHAct, self).init(mobile, password)\n File "/var/user/activity/wolearn/wolearn.py", line 13, in init\n super(WoLearn, self).init(mobile, password)\n File "/var/user/utils/unicomLogin.py", line 32, in init\n self.login()\n File "/var/user/utils/unicomLogin.py", line 100, in login\n "appId": self.getAppId(),\n File "/var/user/utils/unicomLogin.py", line 64, in getAppId\n raise Exception('[UnicomClient]获取appId失败')\nException: [UnicomClient]获取appId失败","statusCode":430}

END RequestId:ec82925d-6c8f-4e8e-8df3-2de568a14693

Report RequestId:ec82925d-6c8f-4e8e-8df3-2de568a14693 Duration:1291ms Memory:128MB MemUsage:63.476562MB

**Comment by fuduxixi** [comment]
解决了。。手机号-1 这个没有改成手机号。。。。shame
