### ISSUE TITLE
大佬这个项目会支持消息推送吗

### ISSUE THREAD

**Issue by jkluio78** [rhming/UnicomDailyTask#5]
https://github.com/qihengfei/dailycheckin/blob/main/utils/message.py
https://github.com/srcrs/unicom-task/blob/main/notify.py
感觉这两个项目的推送都挺全的，希望可以支持消息推送

**Comment by rhming** [comment]
已添加消息推送

**Comment by jkluio78** [comment]
> 已添加消息推送

感谢大佬，大佬辛苦了！
