### ISSUE TITLE
测试正常，推送消息收不到是什么原因？

### ISSUE THREAD

**Issue by fuduxixi** [rhming/UnicomDailyTask#50]
也配置了推送   pushplus  server酱  收不到消息推送？  
还是要在哪里修改？

**Comment by rhming** [comment]
消息推送在指定的两个时间才会推送(11.30和15:30)

**Comment by fuduxixi** [comment]
> 消息推送在指定的两个时间才会推送(11.30和15:30)

现在2021年12月16日 16:18:28 ，看了下运行日志运行都正常，还是收不到消息推送。。

**Comment by rhming** [comment]
那看看`index.py`文件里`PushTemplate`是否配置好需要获取活动日志的账号
