### ISSUE TITLE
你好，我想请问一下这个用户号码为空什么情况呢

### ISSUE THREAD

**Issue by xiaochenbing** [rhming/UnicomDailyTask#51]
![屏幕截图 2021-12-16 163654](https://user-images.githubusercontent.com/86729835/146336785-aeb9b773-9400-481b-8f3a-1aecd27a15e2.png)

**Comment by xiaochenbing** [comment]
![屏幕截图 2021-12-16 163942](https://user-images.githubusercontent.com/86729835/146337158-011db494-aac1-4080-9314-d4ef9f12d2ae.png)
配置的没啥问题呀

**Comment by rhming** [comment]
可能mobile或者openId失效或者错误,可以尝试重新抓包试试

**Comment by xiaochenbing** [comment]
找到原因了，那个配置的+he==在原链接里是%2B和%3D,然后使用原链接的代码就能打开，使用转换后的+和==就打不开，可是只要一配置原链接的代码，运行时就会自动转换为+和==，请问有什么解决方法吗，或者沃邮箱的配置直接使用整条链接可以吗

**Comment by rhming** [comment]
`activity/womail/womail.py`文件中将`self.mobile = unquote(mobile)`改成`self.mobile = mobile`
