### ISSUE TITLE
大家部署完毕后，如何保持代码更新的呢？

### ISSUE THREAD

**Issue by Yacy-wm** [rhming/UnicomDailyTask#55]
感觉部署完毕以后更新起来很麻烦， 尤其是配置信息写在程序里面了，每次都要重新更改，有更好的更新方法嘛？

**Comment by rhming** [comment]
可以将`index.py`文件里的账号配置部分(`XXXTemplate`函数部分)提出来单独一个文件，`index.py`文件里再将其导入
其它配置文件可以先备份再复制粘贴

**Comment by Yacy-wm** [comment]
感谢回复，我自己写了个小脚本，用正则表达式替换了，但是觉得还是如果能把配置文件独立到一个单独的配置文件里可能会方便点，还是谢谢大佬啦
