### ISSUE TITLE
沃学习在哪里领取

### ISSUE THREAD

**Issue by gitiray** [rhming/UnicomDailyTask#56]
请问大佬，前两天我沃学习刮卡活动中了话费，但是一直没到账

是不是应该手动进去领？
入口在哪里呢

**Comment by rhming** [comment]
搜索`知识专区`,不过现在活动好像都下架了

**Comment by rhming** [comment]
活动任务还在,但入口好像没提供

**Comment by gitiray** [comment]
那还有办法兑换吗😂不会直接作废了吧？

**Comment by rhming** [comment]
`activity/wolearn/xxdgg.py`这是刮卡的活动任务,
活动地址`https://edu.10155.com/wact/xxdgg-act.html?jrPlatform=SHOUTING&chc=VXADcwYxB35aH1UfVkZTKAAy&vid=-1`,但打开显示活动已结束了

**Comment by rhming** [comment]
奖品页地址`https://edu.10155.com/wact/xxdgg-act.html?jrPlatform=SHOUTING&chc=VXADcwYxB35aH1UfVkZTKAAy&vid=-1#prize`
需配合油猴脚本执行这段代码`document.getElementsByClassName("actend")[0].remove();`可以进入奖品页
![image](https://user-images.githubusercontent.com/49028484/148221403-27bd8c63-b6f0-4fa0-bd2a-25af8d4592b4.png)

**Comment by gitiray** [comment]
有点可惜刚好昨天过期了😭下次应该能用得上
**谢谢！！！**
