### ISSUE TITLE
请问华为云这是错在哪里了？

### ISSUE THREAD

**Issue by shemc** [rhming/UnicomDailyTask#57]
请问华为云这是错在哪里了？跑不起来，不知道是哪里错了

2022/01/03 18:47:19 GMT+08:00 Start invoke request 'f4085267-a6a1-41e3-8370-ca77ce5b9b1a', version: latest
2022/01/03 18:47:20 GMT+08:00 Finish invoke request 'f4085267-a6a1-41e3-8370-ca77ce5b9b1a', duration: 905.446ms, billing duration: 1000ms, memory used: 106.727MB, rss memory used: 37.648MB.

**Comment by rhming** [comment]
不在执行时间,代码里任务都在指定时间才会执行(大部分任务都是在上午时间段执行)
`index.py`文件里`DEBUG = False`改成`DEBUG = True`开启调试模式所有任务都会执行,也不需要在指定时间才会执行

**Comment by shemc** [comment]
> True

好像还不行  ，改了后，跑一天了还是这样
![snap_screen_20220105190018](https://user-images.githubusercontent.com/44460073/148207349-59cb1545-a080-4f58-b1cf-33e7748ae96c.png)
![snap_screen_20220105190118](https://user-images.githubusercontent.com/44460073/148207359-d8bffcf3-9194-4022-9a34-0159879dde00.png)

**Comment by rhming** [comment]
`index.py`文件里的账号配置了没，`#`号是注释也要去掉
![image](https://user-images.githubusercontent.com/49028484/148218951-097500c6-93db-4fe3-b3e8-bfbca0669eca.png)

**Comment by shemc** [comment]
> `index.py`文件里的账号配置了没，`#`号是注释也要去掉 ![image](https://user-images.githubusercontent.com/49028484/148218951-097500c6-93db-4fe3-b3e8-bfbca0669eca.png)

谢谢！已经ok了，是我自己的问题，没有把#号删除，删除#号后正常了，非常感谢！！！
