### ISSUE TITLE
执行成功一次,之后都是报错

### ISSUE THREAD

**Issue by azhen98** [rhming/UnicomDailyTask#64]
### 为什么要从cookie 里面读取 设备id, 直接拿取设备id不行吗
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 114, in main_handler\n    Template(KldggAct)\n  File \"/var/user/index.py\", line 38, in Template\n    ts.append(Thread(target=cls(mobile, password).run))\n  File \"/var/user/activity/wolearn/kldgg.py\", line 10, in __init__\n    super(KldggAct, self).__init__(mobile, password)\n  File \"/var/user/activity/wolearn/wolearn.py\", line 13, in __init__\n    super(WoLearn, self).__init__(mobile, password)\n  File \"/var/user/utils/unicomLogin.py\", line 34, in __init__\n    self.deviceId = self.global_config['cookie']['d_deviceCode']\nKeyError: 'd_deviceCode'","statusCode":430}

END RequestId:eb911dbc-7e4e-4508-abd8-117b217669bb

**Comment by azhen98** [comment]
## 需要把数据库里面的数据删除重新登录一下, 猜测可能是登录的时候出现失败,判读不够健壮,仍然把数据存进去了

**Comment by azhen98** [comment]
## 不太明白 推送消息的条件是什么, 为什么把 debug 打开之后会推送消息, 但是关闭之后, 也会做任务, 不会推送 pushplus

**Comment by rhming** [comment]
+ `utils/unicomLogin.py`文件里，这行代码可以注释掉或删掉`self.deviceId = self.global_config['cookie']['d_deviceCode']`，之前没有登录限制设备Id都是随机生成的，后面才加上的设备Id配置
![image](https://user-images.githubusercontent.com/49028484/150789088-af9106cb-9cbf-4c9c-8db3-efa01013843f.png)
+ 出现这种应该是登录了多台设备被挤下线，但为了减少账号因登录次数过多导致异常，不会自动`login`只会以`online`的方式更新Cookie
+ 可能因手机授予联通App的权限不同的原因，会导致appId或设备id发生改变，出现登录多台设备而挤下线，设备Id填写最准确的还是抓包获取到Cookie中的`d_deviceCode`
