### ISSUE TITLE
华为云函数可以像腾讯云函数那样在线编辑吗

### ISSUE THREAD

**Issue by jkluio78** [rhming/UnicomDailyTask#7]
部署后好像没法编辑配置文件

**Comment by rhming** [comment]
选择在线编辑,黑色区域右上角有个伸展选项，华为云函数工作流只是纯文本编辑器
![image](https://user-images.githubusercontent.com/49028484/135701553-732d2aeb-ab91-4da5-884b-a10760c46937.png)

**Comment by jkluio78** [comment]
解决了
