### ISSUE TITLE
挂了三个号全黑了

### ISSUE THREAD

**Issue by onesixsix** [rhming/UnicomDailyTask#71]
一直挂着，从今年开始陆陆续续的黑了，领奖励显示火爆，有的号不能签到能领奖励，有的只能签到，领不了奖励，希望看一下怎么回事

**Comment by rhming** [comment]
**尽量不要领定向积分，把定向积分用完，可以拿去抽奖，定向积分多了容易风控**，现在时好时坏 今天领不了过一两天又可以领

**Comment by onesixsix** [comment]
好的，一会用完
