### ISSUE TITLE
沃学习也有黑名单吗

### ISSUE THREAD

**Issue by gitiray** [rhming/UnicomDailyTask#74]
今天刮卡活动中了个话费，但是没到账，我就去活动页面看了，发现没被领取，点击领取就提示“当前帐号暂无活动参与资格”
挺奇怪的描述，都已经抽中了在奖品列表里，难道意思是我被拉黑了？

**Comment by rhming** [comment]
这个不知道,没遇到过这种情况,反馈客服看能不能解决

**Comment by gitiray** [comment]
算了，没问客服，不然倒打一耙
