### ISSUE TITLE
沃邮箱网页版有个每日“沃邮箱网页版登录 +5积分”的任务

### ISSUE THREAD

**Issue by lly8666** [rhming/UnicomDailyTask#75]
不知道是否方便加进去

**Comment by rhming** [comment]
任务其实在里面,只不过获取的方式变了
`activity/womail/webmail.py`文件中将
`            if task['resourceName'] in ['沃邮箱网页版登录'] and task['taskState'] == 0:`
改成
`            if False and task['resourceName'] in ['沃邮箱网页版登录'] and task['taskState'] == 0:`

**Comment by lly8666** [comment]
> 任务其实在里面,只不过获取的方式变了 `activity/womail/webmail.py`文件中将 ` if task['resourceName'] in ['沃邮箱网页版登录'] and task['taskState'] == 0:` 改成 ` if False and task['resourceName'] in ['沃邮箱网页版登录'] and task['taskState'] == 0:`

感谢，已搞定~
