### ISSUE TITLE
appid获取不到

### ISSUE THREAD

**Issue by superHao2000** [rhming/UnicomDailyTask#78]
### **日志**
START RequestId:987cf14b-4298-4fc1-9120-5c0acf744154

###########################readCookie########################### 18628528275

Starting new HTTPS connection (1): superhao.pythonanywhere.com:443

https://superhao.pythonanywhere.com:443 "GET /?key=18628528275WoGame HTTP/1.1" 200 38

#############################login############################## 18628528275

###########################JSEncrypt############################ 18628528275

###########################JSEncrypt############################ 18628528275

############################getAppId############################ 18628528275

ERROR RequestId:987cf14b-4298-4fc1-9120-5c0acf744154 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 139, in main_handler\n    Template (SigninApp)\n  File \"/var/user/index.py\", line 41, in Template\n    ts.append (Thread (target=cls (mobile, password).run))\n  File \"/var/user/activity/unicom/dailySign.py\", line 16, in __init__\n    super (SigninApp, self).__init__(mobile, password)\n  File \"/var/user/utils/unicomLogin.py\", line 32, in __init__\n    self.login ()\n  File \"/var/user/utils/unicomLogin.py\", line 100, in login\n    \"appId\": self.getAppId (),\n  File \"/var/user/utils/unicomLogin.py\", line 64, in getAppId\n    raise Exception ('[UnicomClient] 获取 appId 失败 ')\nException: [UnicomClient] 获取 appId 失败","statusCode":430}

END RequestId:987cf14b-4298-4fc1-9120-5c0acf744154

Report RequestId:987cf14b-4298-4fc1-9120-5c0acf744154 Duration:1693ms Memory:128MB MemUsage:34.283485MB
### **appid.json内容**
{
  "手机号-1": "86b8be06f56ba55e9fa7dff134c6b16cd0a85beeac23c36244ef67f513048d53fab1ad6f2c1f1430f42b7ce47aff44605467ba4278865331baa23a7fba0a5d77429d4c956053fee2834a2d632b68c1d0",
  "手机号-2": "联通appId-2"
}

**Comment by Disky** [comment]
appid.json里“手机号-1”改成“18628528275”
