### ISSUE TITLE
无推送，问下怎么回事

### ISSUE THREAD

**Issue by zhouyang2021** [rhming/UnicomDailyTask#8]
填了推送。配置了数据接口，里面没数据，华为云函数

**Comment by rhming** [comment]
搭建的数据存储服务管理后台没有数据吗
推送日志每天都是在固定时间段

**Comment by zhouyang2021** [comment]
没数据，测试几次成功，后台没数据也没推送

**Comment by rhming** [comment]
把index.py里面的`DEBUG = False`改为`DEBUG = True`在测试一遍(执行之间比较长)，测试完再改回去，看看后台有没有数据
![image](https://user-images.githubusercontent.com/49028484/135756160-88d26b97-2dbb-4999-a8c5-17c4d3428cf9.png)

**Comment by zhouyang2021** [comment]
有数据，函数执行失败 函数返回:

{ "errorMessage": "[WoRead]\u767b\u5f55\u5931\u8d25,\u7ed3\u675f\u6267\u884c\u4efb\u52a1", "errorType": "Exception", "stackTrace": [ "File \"./index.py\", line 82, in main_handler", " Template(LuckDraw)", "File \"./index.py\", line 31, in Template", " ts.append(Thread(target=cls(mobile, password).run))", "File \"./activity/woread/luckdraw.py\", line 9, in __init__", " super(LuckDraw, self).__init__(mobile)", "File \"./activity/woread/woread.py\", line 30, in __init__", " self.login()", "File \"./activity/woread/woread.py\", line 80, in login", " raise Exception('[WoRead]\u767b\u5f55\u5931\u8d25,\u7ed3\u675f\u6267\u884c\u4efb\u52a1')" ] }

**Comment by rhming** [comment]
这提示沃阅读登录失败，在尝试一次看看(可能)
应该还有其他数据输出，截个图看看

**Comment by rhming** [comment]
> 这提示沃阅读登录失败，在尝试一次看看(可能) 应该还有其他数据输出，截个图看看
登录接口也正常，没失效
![image](https://user-images.githubusercontent.com/49028484/135757045-a7f3bc6d-c47a-4748-a9ff-d9c0f7036d35.png)

**Comment by zhouyang2021** [comment]
![IMG_20211003_220423.jpg](https://user-images.githubusercontent.com/90887733/135757215-7c8320d9-caca-413d-9d8b-4cb64b5d8b55.jpg)

**Comment by rhming** [comment]
沃阅读账号没注册 [m.iread.wo.cn](https://m.iread.wo.cn/index.action?indexType=book) 使用账号登录，去注册一下

**Comment by rhming** [comment]
联通appid没配置好，相关配置文件都要配置好（号码要对应，不能有错误）
![image](https://user-images.githubusercontent.com/49028484/135758096-668abe1c-64ec-453b-831f-42084ed3e2ae.png)
