### ISSUE TITLE
小说里面超级大转盘任务没全完成

### ISSUE THREAD

**Issue by onesixsix** [rhming/UnicomDailyTask#82]
上月任务应该都完成了，今天看了看视频任务没做，阅读差20个没全完成，必得30话费那个，别的任务都领不了奖励了，号全黑了，只剩下这个任务过日子了，希望大佬看一下怎么回事，刚看了看好像不能自动抽奖了

**Comment by Disky** [comment]
黑了 太正常了

**Comment by onesixsix** [comment]
> 黑了太正常了

手动看视频可以，应该是视频参数改了

**Comment by rhming** [comment]
已更新

**Comment by onesixsix** [comment]
感谢大佬

**Comment by onesixsix** [comment]
![1](https://user-images.githubusercontent.com/82140041/156554709-26813023-12eb-40a0-bc92-30cc2fcd4816.jpg)
刚看了看，阅读那个还是没有做满，50个做了30个，手动可以做满，应该不是号的问题

**Comment by onesixsix** [comment]
刚看了看，全完成了，应该是我看的时候任务没全完成
