### ISSUE TITLE
沃学习活动 失效 未登录状态

### ISSUE THREAD

**Issue by rubnet** [rhming/UnicomDailyTask#99]
请问沃学习活动是 知识专区>联通学堂 吗？
其他活动签到正常
###########################readCookie########################### 132429xxx6
#########################popupListInfo########################## 132429xxx6
##############################run############################### 132429xxx6
#############################index############################## 132429xxx6
132429xxx6抽奖-xxxxx=
#############################doDraw############################# 132429xxx6
{'code': '9999', 'message': '今天已经抽过一次奖了', 'innercode': '9999'}
'prizedesc'
###########################readCookie########################### 132429xxx6
#########################popupListInfo########################## 132429xxx6
##############################run############################### 132429xxx6
###########################readCookie########################### 132429xxx6
#########################popupListInfo########################## 132429xxx6
##############################run############################### 132429xxx6
###########################readCookie########################### 132429xxx6
#########################popupListInfo########################## 132429xxx6
##############################run############################### 132429xxx6
###########################parsePrize########################### 132429xxx6
###########################readCookie########################### 132429xxx6
#############################login############################## 132429xxx6
###########################JSEncrypt############################ 132429xxx6
###########################JSEncrypt############################ 132429xxx6
############################getAppId############################ 132429xxx6
{"dsc":"您输入的密码错误，请重新输入或使用短信验证码登录。","code":"4"}

Traceback (most recent call last):
  File "/ql/config/UnicomDailyTask/index.py", line 171, in <module>
    main_handler()
  File "/ql/config/UnicomDailyTask/index.py", line 123, in main_handler
    Template(KldggAct)
  File "/ql/config/UnicomDailyTask/index.py", line 42, in Template
    ts.append(Thread(target=cls(mobile, password).run))
  File "/ql/config/UnicomDailyTask/activity/wolearn/kldgg.py", line 10, in __init__
    super(KldggAct, self).__init__(mobile, password)
  File "/ql/config/UnicomDailyTask/activity/wolearn/wolearn.py", line 13, in __init__
    super(WoLearn, self).__init__(mobile, password)
  File "/ql/config/UnicomDailyTask/utils/unicomLogin.py", line 37, in __init__
    raise Exception('[UnicomClient]未登录状态')
Exception: [UnicomClient]未登录状态

**Comment by a369626013** [comment]
你好，你这是怎么搭建成功的，我的为啥不能运行

**Comment by checkvip** [comment]
https://thin-hill-428.notion.site/1c598629675145988b43a37998a1604a

cqd5686 ***@***.***> 于 2023年2月15日周三 01:40写道：
